name: Towny
version: '${project.version}'
main: online.bingulhan.towny.Towny
authors: [ BingulHan ]
commands:
  town:
    description: Towny ana komutu
  townfounder:
    description: Towny Lider ana komutu
